from application.telegram.keyboards.authorization_keyboards import AuthorizationKeyboardsBuilder
from application.telegram.keyboards.canteens_keyboards import CanteensKeyboardsBuilder
from application.telegram.keyboards.links_keyboards import LinksKeyboardsBuilder
from application.telegram.keyboards.menu_main_keyboards import MenuMainKeyboardsBuilder
from application.telegram.keyboards.navigator_keyboards import NavigatorKeyboardsBuilder
from application.telegram.keyboards.settings_keyboards import SettingsKeyboardsBuilder
from application.telegram.keyboards.stadburo_keyboards import StadburoKeyboardsBuilder
from infrastructure.config.services_config import translation_service

canteens_keyboards = CanteensKeyboardsBuilder(translation_service=translation_service)
stadburo_keyboards = StadburoKeyboardsBuilder(translation_service=translation_service)
settings_keyboards = SettingsKeyboardsBuilder(translation_service=translation_service)
navigator_keyboards = NavigatorKeyboardsBuilder(translation_service=translation_service)
links_keyboards = LinksKeyboardsBuilder(translation_service=translation_service)
menu_main_keyboards = MenuMainKeyboardsBuilder(translation_service=translation_service)

authorization_keyboards = AuthorizationKeyboardsBuilder(
    translation_service=translation_service,
    settings_keyboards=settings_keyboards,
)




